### ISSUE TITLE
Seg fault: NameError: name 'freq_field_id' is not defined

### ISSUE THREAD

**Issue by andimik** [deeptho/neumodvb#39]
```
$ neumodvb 
loading options from /etc/neumodvb/neumodvb.cfg
loading options from /home/andreas/.config/neumodvb/neumodvb.cfg
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/neumodvb/neumolist.py", line 1321, in ShowFilter
    self.OnRefresh(evt=None)
  File "/usr/local/lib/python3.12/dist-packages/neumodvb/neumolist.py", line 1424, in OnRefresh
    self.table.__get_data__()
  File "/usr/local/lib/python3.12/dist-packages/neumodvb/neumolist.py", line 935, in __get_data__
    self.screen_getter(txn, subfield)
  File "/usr/local/lib/python3.12/dist-packages/neumodvb/satlist.py", line 70, in <lambda>
    screen_getter = lambda txn, subfield: self.screen_getter_xxx(txn, subfield)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/neumodvb/satlist.py", line 110, in screen_getter_xxx
    match_data, matchers = self.filter_band_(self.parent.sat_band)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/neumodvb/satlist.py", line 97, in filter_band_
    if m.field_id == freq_field_id:
                     ^^^^^^^^^^^^^
NameError: name 'freq_field_id' is not defined
python3: /home/andreas/apps/neumodvb/src/receiver/subscriber.cc:102: int subscriber_t::scan_bands(const ss::vector_<chdb::sat_t> &, const std::optional<devdb::tune_options_t> &, const devdb::band_scan_options_t &): Assertion `ret == get_subscription_id() || (int) ret == -1' failed.
Abgebrochen (Speicherabzug geschrieben)

```

**Comment by deeptho** [comment]
Try the latest version...
